"""Public API for the PolyGeo simplicial core."""

from .geometry import Geometry, GeometryError
from .operators import (
    DualCochainSpace,
    LinearMap,
    OperatorError,
    exterior_derivative,
    hodge_star,
)
from .simplicial import (
    ORDINARY_FORM,
    BoundaryState,
    BoundaryUnknown,
    Closed,
    CochainSpace,
    Complex,
    Connected,
    ConnectivityState,
    ConnectivityUnknown,
    FieldSemantics,
    Form,
    OneForm,
    OrdinaryForm,
    OrientationState,
    OrientationUnknown,
    Oriented,
    Simplicial,
    SimplicialError,
    SimplexSubset,
    TopologyState,
    TriangleManifold,
    TwoForm,
    ZeroForm,
)

__all__ = [
    "ORDINARY_FORM",
    "BoundaryState",
    "BoundaryUnknown",
    "Closed",
    "CochainSpace",
    "Complex",
    "Connected",
    "ConnectivityState",
    "ConnectivityUnknown",
    "DualCochainSpace",
    "FieldSemantics",
    "Form",
    "Geometry",
    "GeometryError",
    "LinearMap",
    "OneForm",
    "OrdinaryForm",
    "OrientationState",
    "OrientationUnknown",
    "OperatorError",
    "Oriented",
    "SimplexSubset",
    "Simplicial",
    "SimplicialError",
    "TopologyState",
    "TriangleManifold",
    "TwoForm",
    "ZeroForm",
    "exterior_derivative",
    "hodge_star",
]
