"""Typing surface for the private mandatory native extension."""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray
from collections.abc import Iterable, Mapping, Sequence
from fractions import Fraction
from typing import Any, Callable, Literal, Never, Protocol, Self, final, overload

from scipy.sparse import csr_array

type ExactScalar = int | Fraction
type Coordinates[Scalar: ExactScalar] = (
    Mapping[int, Scalar] | Iterable[tuple[int, Scalar]]
)

class ChainError(ValueError):
    @property
    def reason(self) -> str: ...
    @property
    def details(self) -> Mapping[str, object]: ...

class ChainLawLimit:
    def __init__(
        self,
        *,
        retained_logical_bytes: int = ...,
        peak_live_logical_bytes: int = ...,
        terms: int = ...,
    ) -> None: ...
    @property
    def retained_logical_bytes(self) -> int: ...
    @property
    def peak_live_logical_bytes(self) -> int: ...
    @property
    def terms(self) -> int: ...

class IntegerRing: ...
class RationalField: ...

ZZ: IntegerRing
QQ: RationalField

class Chain:
    variance: Literal["chain"]

class Cochain:
    variance: Literal["cochain"]

class BigIntEncoding:
    _kind: Literal["bigint"]

class ReducedFractionEncoding:
    _kind: Literal["fraction"]

class Space[Scalar: ExactScalar, Variance, Degree: int]:
    _variance_proof: Variance
    @property
    def degree(self) -> int: ...
    @property
    def dimension(self) -> int: ...
    def element(self, coordinates: Coordinates[Scalar]) -> Element[Self]: ...

class Element[SpaceType: Space[Any, Any, int]]:
    _proof: SpaceType
    @property
    def degree(self) -> int: ...
    @property
    def dimension(self) -> int: ...
    def to_python_copy(self) -> tuple[tuple[int, ...], tuple[ExactScalar, ...]]: ...
    def evaluate[Scalar: ExactScalar, Degree: int](
        self: Element[Space[Scalar, Cochain, Degree]],
        chain: Element[Space[Scalar, Chain, Degree]],
    ) -> Scalar: ...
    def cup[Scalar: ExactScalar](
        self: Element[Space[Scalar, Cochain, int]],
        other: Element[Space[Scalar, Cochain, int]],
    ) -> Element[Space[Scalar, Cochain, int]]: ...
    def wedge(
        self: Element[Space[Fraction, Cochain, int]],
        other: Element[Space[Fraction, Cochain, int]],
    ) -> Element[Space[Fraction, Cochain, int]]: ...

class LinearMap[SourceSpace: Space[Any, Any, int], TargetSpace: Space[Any, Any, int]]:
    @property
    def source(self) -> SourceSpace: ...
    @property
    def target(self) -> TargetSpace: ...
    def apply(self, value: Element[SourceSpace]) -> Element[TargetSpace]: ...
    @overload
    def dual[Scalar: ExactScalar, SourceDegree: int, TargetDegree: int](
        self: LinearMap[
            Space[Scalar, Chain, SourceDegree],
            Space[Scalar, Chain, TargetDegree],
        ],
    ) -> LinearMap[
        Space[Scalar, Cochain, TargetDegree],
        Space[Scalar, Cochain, SourceDegree],
    ]: ...
    @overload
    def dual[Scalar: ExactScalar, SourceDegree: int, TargetDegree: int](
        self: LinearMap[
            Space[Scalar, Cochain, SourceDegree],
            Space[Scalar, Cochain, TargetDegree],
        ],
    ) -> LinearMap[
        Space[Scalar, Chain, TargetDegree],
        Space[Scalar, Chain, SourceDegree],
    ]: ...
    def compose[
        Initial: Space[Any, Any, int],
        Middle: Space[Any, Any, int],
        Final: Space[Any, Any, int],
    ](
        self: LinearMap[Middle, Final], before: LinearMap[Initial, Middle]
    ) -> LinearMap[Initial, Final]: ...
    def over[SourceVariance, TargetVariance, SourceDegree: int, TargetDegree: int](
        self: LinearMap[
            Space[int, SourceVariance, SourceDegree],
            Space[int, TargetVariance, TargetDegree],
        ],
        coefficients: RationalField,
    ) -> LinearMap[
        Space[Fraction, SourceVariance, SourceDegree],
        Space[Fraction, TargetVariance, TargetDegree],
    ]: ...

class ChainComplex[Scalar: ExactScalar]:
    _coefficient_proof: Scalar
    @property
    def coefficient_system(self) -> str: ...
    @property
    def dimension(self) -> int: ...
    def same_owner(self, other: ChainComplex[Any]) -> bool: ...
    def __getitem__[Degree: int](
        self, degree: Degree
    ) -> Space[Scalar, Chain, Degree]: ...
    def dual(self) -> CochainComplex[Scalar]: ...
    def boundary(
        self, degree: int
    ) -> LinearMap[Space[Scalar, Chain, int], Space[Scalar, Chain, int]]: ...
    def over(
        self: ChainComplex[int], coefficients: RationalField
    ) -> ChainComplex[Fraction]: ...

class CochainComplex[Scalar: ExactScalar]:
    _coefficient_proof: Scalar
    def __getitem__[Degree: int](
        self, degree: Degree
    ) -> Space[Scalar, Cochain, Degree]: ...
    def coboundary(
        self, degree: int
    ) -> LinearMap[Space[Scalar, Cochain, int], Space[Scalar, Cochain, int]]: ...

class ChainIsomorphism[Scalar: ExactScalar]:
    @property
    def source(self) -> ChainComplex[Scalar]: ...
    @property
    def target(self) -> ChainComplex[Scalar]: ...
    def forward[Degree: int](
        self, degree: Degree
    ) -> LinearMap[Space[Scalar, Chain, Degree], Space[Scalar, Chain, Degree]]: ...
    def inverse[Degree: int](
        self, degree: Degree
    ) -> LinearMap[Space[Scalar, Chain, Degree], Space[Scalar, Chain, Degree]]: ...
    def signed_permutation_numpy_copy(
        self, degree: int
    ) -> tuple[NDArray[np.int64], NDArray[np.int8]]: ...

class CsrEstimate:
    shape: tuple[int, int]
    nnz_bound: int
    coefficient_bits_bound: int
    retained_logical_bytes_bound: int
    peak_live_logical_bytes_bound: int
    scratch_entries_bound: int
    scalar_steps_bound: int
    canonicalization_required: bool
    def as_limit(self) -> CsrBuildLimit: ...

class CsrBuildLimit:
    retained_logical_bytes: int
    peak_live_logical_bytes: int
    coefficient_bits: int
    scalar_steps: int
    def replace(
        self,
        *,
        retained_logical_bytes: int | None = None,
        peak_live_logical_bytes: int | None = None,
        coefficient_bits: int | None = None,
        scalar_steps: int | None = None,
    ) -> CsrBuildLimit: ...

class IntegerCsrParts:
    row_offsets: NDArray[Any]
    column_indices: NDArray[Any]
    coefficients: tuple[int, ...]
    shape: tuple[int, int]

class RationalCsrParts:
    row_offsets: NDArray[Any]
    column_indices: NDArray[Any]
    numerators: tuple[int, ...]
    denominators: tuple[int, ...]
    shape: tuple[int, int]

class Csr[
    SourceSpace: Space[Any, Any, int],
    TargetSpace: Space[Any, Any, int],
    Encoding,
]:
    represented_map: LinearMap[SourceSpace, TargetSpace]
    encoding: type[Encoding]
    @staticmethod
    def estimate[
        Source: Space[Any, Any, int],
        Target: Space[Any, Any, int],
        EncodingType,
    ](map_: LinearMap[Source, Target], encoding: type[EncodingType]) -> CsrEstimate: ...
    @classmethod
    @overload
    def build[Source: Space[Any, Any, int], Target: Space[Any, Any, int]](
        cls,
        map_: LinearMap[Source, Target],
        encoding: type[BigIntEncoding],
        limit: CsrBuildLimit,
    ) -> Csr[Source, Target, BigIntEncoding]: ...
    @classmethod
    @overload
    def build[Source: Space[Any, Any, int], Target: Space[Any, Any, int]](
        cls,
        map_: LinearMap[Source, Target],
        encoding: type[ReducedFractionEncoding],
        limit: CsrBuildLimit,
    ) -> Csr[Source, Target, ReducedFractionEncoding]: ...
    def apply(self, value: Element[SourceSpace]) -> Element[TargetSpace]: ...
    @overload
    def to_python_copy(
        self: Csr[SourceSpace, TargetSpace, BigIntEncoding],
    ) -> IntegerCsrParts: ...
    @overload
    def to_python_copy(
        self: Csr[SourceSpace, TargetSpace, ReducedFractionEncoding],
    ) -> RationalCsrParts: ...
    def to_scipy_int64_copy(
        self: Csr[SourceSpace, TargetSpace, BigIntEncoding],
    ) -> csr_array: ...

class HomologyError(ChainError):
    @property
    def reason(self) -> str: ...
    @property
    def details(self) -> Mapping[str, object]: ...

@final
class HomologyLimit:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def retained_logical_bytes(self) -> int: ...
    @property
    def peak_live_logical_bytes(self) -> int: ...
    @property
    def coefficient_bits(self) -> int: ...
    @property
    def smith_steps(self) -> int: ...
    def replace(
        self,
        *,
        retained_logical_bytes: int | None = None,
        peak_live_logical_bytes: int | None = None,
        coefficient_bits: int | None = None,
        smith_steps: int | None = None,
    ) -> HomologyLimit: ...

DEFAULT_HOMOLOGY_LIMIT: HomologyLimit

@final
class HomologyGroup[Degree: int]:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def degree(self) -> Degree: ...
    @property
    def free_rank(self) -> int: ...
    @property
    def torsion_orders(self) -> tuple[int, ...]: ...
    def free_cycle(self, index: int) -> Element[Space[int, Chain, Degree]]: ...
    def torsion_cycle(self, index: int) -> Element[Space[int, Chain, Degree]]: ...
    def torsion_bound(self, index: int) -> Element[Space[int, Chain, Degree]]: ...

@final
class IntegralHomology:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def degrees(self) -> tuple[int, ...]: ...
    def __getitem__[Degree: int](self, degree: Degree) -> HomologyGroup[Degree]: ...

def analyze_integral_homology(
    chain_complex: ChainComplex[int],
    degrees: Iterable[int],
    *,
    limit: HomologyLimit = DEFAULT_HOMOLOGY_LIMIT,
) -> IntegralHomology: ...

DEFAULT_LAW_LIMIT: ChainLawLimit

class SimplicialError(ValueError):
    @property
    def reason(self) -> str: ...
    @property
    def details(self) -> Mapping[str, int | str]: ...

class HalfedgeError(SimplicialError): ...

class _GeometryDomain(Protocol):
    @property
    def vertex_count(self) -> int: ...
    @property
    def dimension(self) -> int: ...
    def simplex_count(self, degree: int) -> int: ...
    def simplices_numpy_copy(self, degree: int) -> NDArray[np.int64]: ...
    def shares_data_with(self, other: Complex) -> bool: ...

class GeometryError(ValueError):
    reason: str
    details: Mapping[str, int | str]

class FormElementError(ValueError):
    reason: str

class OperatorError(ValueError):
    reason: str

class ProblemError(ValueError):
    reason: str
    details: Mapping[str, int | str]

class SolveError(ValueError):
    reason: str
    details: Mapping[str, int | str]

class SurfaceError(ValueError):
    reason: str
    details: Mapping[str, int | str]

class GeometryLimit:
    def __init__(
        self,
        *,
        retained_logical_bytes: int = ...,
        peak_live_logical_bytes: int = ...,
        coefficient_bits: int = ...,
        exact_steps: int = ...,
    ) -> None: ...
    @property
    def retained_logical_bytes(self) -> int: ...
    @property
    def peak_live_logical_bytes(self) -> int: ...
    @property
    def coefficient_bits(self) -> int: ...
    @property
    def exact_steps(self) -> int: ...

DEFAULT_GEOMETRY_LIMIT: GeometryLimit

class FormSpace[Variance: str, Degree: int]:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def degree(self) -> Degree: ...
    @property
    def size(self) -> int: ...
    @property
    def variance(self) -> Variance: ...
    @property
    def is_full(self) -> bool: ...
    def same_space(self, other: FormSpace[Any, Any]) -> bool: ...
    def admit_numpy(
        self, coefficients: NDArray[np.float64]
    ) -> FormElement[Variance, Degree]: ...
    def realize_integral(self, exact: object) -> FormElement[Variance, Degree]: ...
    def identity(self) -> FormOperator[Variance, Degree, Variance, Degree]: ...
    def zero_to[TargetVariance: str, TargetDegree: int](
        self, target: FormSpace[TargetVariance, TargetDegree]
    ) -> FormOperator[Variance, Degree, TargetVariance, TargetDegree]: ...
    def restriction(self) -> FormOperator[Variance, Degree, Variance, Degree]: ...
    def extension_by_zero(
        self,
    ) -> FormOperator[Variance, Degree, Variance, Degree]: ...
    def exterior_derivative(
        self,
    ) -> FormOperator[Variance, Degree, Variance, int]: ...

class FormElement[Variance: str, Degree: int]:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def space(self) -> FormSpace[Variance, Degree]: ...
    def coefficients_numpy_copy(self) -> NDArray[np.float64]: ...
    def __neg__(self) -> FormElement[Variance, Degree]: ...
    def apply[TargetVariance: str, TargetDegree: int](
        self,
        operator: FormOperator[Variance, Degree, TargetVariance, TargetDegree],
    ) -> FormElement[TargetVariance, TargetDegree]: ...
    def wedge(
        self: FormElement[Literal["cochain"], int],
        other: FormElement[Literal["cochain"], int],
    ) -> FormElement[Literal["cochain"], int]: ...

class FormOperator[
    SourceVariance: str,
    SourceDegree: int,
    TargetVariance: str,
    TargetDegree: int,
]:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def source(self) -> FormSpace[SourceVariance, SourceDegree]: ...
    @property
    def target(self) -> FormSpace[TargetVariance, TargetDegree]: ...
    @property
    def execution_steps(self) -> int: ...
    def same_identity(self, other: FormOperator[Any, Any, Any, Any]) -> bool: ...
    def apply(
        self, value: FormElement[SourceVariance, SourceDegree]
    ) -> FormElement[TargetVariance, TargetDegree]: ...
    def compose[BeforeVariance: str, BeforeDegree: int](
        self,
        before: FormOperator[
            BeforeVariance, BeforeDegree, SourceVariance, SourceDegree
        ],
    ) -> FormOperator[BeforeVariance, BeforeDegree, TargetVariance, TargetDegree]: ...
    def dirichlet(
        self,
        rhs: FormElement[TargetVariance, TargetDegree],
        prescribed: FormElement[TargetVariance, TargetDegree],
    ) -> Problem[DirichletResult]: ...

type FormChainSpace[Degree: int] = FormSpace[Literal["chain"], Degree]
type FormCochainSpace[Degree: int] = FormSpace[Literal["cochain"], Degree]
type FormChain[Degree: int] = FormElement[Literal["chain"], Degree]
type FormCochain[Degree: int] = FormElement[Literal["cochain"], Degree]

class Geometry[K: _GeometryDomain]:
    def __init__(
        self,
        complex: K,
        positions: NDArray[np.float64],
        *,
        limit: GeometryLimit = DEFAULT_GEOMETRY_LIMIT,
    ) -> None: ...
    @staticmethod
    def from_positions[Domain: _GeometryDomain](
        complex: Domain,
        positions: NDArray[np.float64],
        *,
        limit: GeometryLimit = DEFAULT_GEOMETRY_LIMIT,
    ) -> Geometry[Domain]: ...
    @property
    def topology(self) -> K: ...
    @property
    def ambient_dimension(self) -> int: ...
    def positions_numpy_copy(self) -> NDArray[np.float64]: ...
    def primal_measures_numpy_copy(self, degree: int) -> NDArray[np.float64]: ...
    def dual_measures_numpy_copy(self, degree: int) -> NDArray[np.float64]: ...
    def metric(self) -> Metric[K]: ...

class Metric[K: _GeometryDomain]:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def geometry(self) -> Geometry[K]: ...
    def hodge_coefficients_numpy_copy(self, degree: int) -> NDArray[np.float64]: ...
    def riesz(self, degree: int) -> FormOperator[Any, Any, Any, Any]: ...
    def inverse_riesz(self, degree: int) -> FormOperator[Any, Any, Any, Any]: ...
    def codifferential(self, degree: int) -> FormOperator[Any, Any, Any, Any]: ...
    def laplacian(self, degree: int) -> FormOperator[Any, Any, Any, Any]: ...
    def harmonic_basis(
        self,
        group: HomologyGroup[Literal[1]],
        *,
        policy: Policy | None = None,
        cancellation: CancellationToken | None = None,
    ) -> HarmonicBasis: ...
    def mean_zero_poisson_density[Degree: int](
        self, density: FormCochain[Degree]
    ) -> Problem[PoissonResult]: ...
    def mean_zero_poisson_load[Degree: int](
        self, load: FormChain[Degree]
    ) -> Problem[PoissonResult]: ...
    def harmonic_extension(
        self, values: FormElement[Any, Any]
    ) -> Problem[DirichletResult]: ...
    def hodge_decomposition(
        self, source: FormElement[Any, Any]
    ) -> Problem[HodgeDecomposition]: ...
    def heat_evolution(
        self, source: FormElement[Any, Any], time_step: float
    ) -> Problem[HeatResult]: ...
    def frozen_mean_curvature_flow(
        self,
        time_step: float,
        *,
        limit: GeometryLimit | None = None,
        policy: Policy | None = None,
        cancellation: CancellationToken | None = None,
    ) -> FlowStep: ...

class StorageLimit:
    def __init__(
        self, retained_logical_bytes: int, peak_live_logical_bytes: int
    ) -> None: ...
    @property
    def retained_logical_bytes(self) -> int: ...
    @property
    def peak_live_logical_bytes(self) -> int: ...

class WorkLimit:
    def __init__(self, steps: int) -> None: ...
    @property
    def steps(self) -> int: ...

class Executor:
    @staticmethod
    def sequential() -> Executor: ...

class Policy:
    def __init__(
        self,
        *,
        executor: Executor | None = None,
        storage: StorageLimit | None = None,
        work: WorkLimit | None = None,
    ) -> None: ...
    @property
    def executor(self) -> Executor: ...
    @property
    def storage(self) -> StorageLimit: ...
    @property
    def work(self) -> WorkLimit: ...

class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def is_cancelled(self) -> bool: ...

class Problem[SolutionT]:
    def __new__(cls, _token: Never, /) -> Self: ...
    def prepare(
        self,
        *,
        policy: Policy | None = None,
        cancellation: CancellationToken | None = None,
    ) -> Prepared[SolutionT]: ...

class Prepared[SolutionT]:
    def __new__(cls, _token: Never, /) -> Self: ...
    def workspace_for(self, problem: Problem[SolutionT]) -> Workspace: ...
    def solve(
        self,
        problem: Problem[SolutionT],
        workspace: Workspace,
        *,
        cancellation: CancellationToken | None = None,
    ) -> SolutionT: ...

class Workspace:
    def __new__(cls, _token: Never, /) -> Self: ...

class PoissonResult:
    @property
    def potential(self) -> FormElement[Any, Any]: ...
    @property
    def residual_bound(self) -> float: ...
    @property
    def gauge_bound(self) -> float: ...
    @property
    def exact_fallback_rows(self) -> int: ...

class DirichletResult:
    @property
    def value(self) -> FormElement[Any, Any]: ...
    @property
    def residual_bound(self) -> float: ...
    @property
    def exact_fallback_rows(self) -> int: ...

class HodgeDecomposition:
    @property
    def exact(self) -> FormElement[Any, Any]: ...
    @property
    def coexact(self) -> FormElement[Any, Any]: ...
    @property
    def harmonic(self) -> FormElement[Any, Any]: ...
    @property
    def reconstruction_bound(self) -> float: ...
    @property
    def orthogonality_bound(self) -> float: ...

@final
class HarmonicBasis:
    @property
    def rank(self) -> int: ...
    @property
    def forms(self) -> tuple[FormCochain[Literal[1]], ...]: ...
    @property
    def maximum_closedness_residual(self) -> float: ...
    @property
    def maximum_coclosedness_residual(self) -> float: ...
    @property
    def maximum_identity_period_residual(self) -> float: ...
    @property
    def residual_limit(self) -> float: ...

class HeatResult:
    @property
    def value(self) -> FormElement[Any, Any]: ...
    @property
    def residual_bound(self) -> float: ...
    @property
    def mass_residual_bound(self) -> float: ...
    @property
    def energy_before(self) -> float: ...
    @property
    def energy_after(self) -> float: ...
    @property
    def exact_fallback_rows(self) -> int: ...

class FlowStep:
    @property
    def geometry(self) -> Geometry[Any]: ...
    @property
    def energy_before(self) -> float: ...
    @property
    def energy_after(self) -> float: ...
    @property
    def residual_bound(self) -> float: ...
    @property
    def centroid_residual_bound(self) -> float: ...

class ConformalMap:
    @property
    def geometry(self) -> Geometry[Any]: ...
    @property
    def required_rank(self) -> int: ...
    @property
    def observed_rank(self) -> int: ...
    @property
    def condition_indicator(self) -> float: ...
    @property
    def residual_bound(self) -> float: ...
    @property
    def minimum_normalized_signed_twice_area(self) -> float: ...
    @property
    def exact_fallback_faces(self) -> int: ...

class TriangleSurface:
    @staticmethod
    def admit(realization: Geometry[Any]) -> TriangleSurface: ...
    @property
    def geometry(self) -> Geometry[Any]: ...
    @property
    def face_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    def vertex_field(self, values: NDArray[np.float64]) -> VertexField: ...
    def face_field(self, values: NDArray[np.float64]) -> FaceField: ...
    def gradient(self, source: FormCochain[int]) -> FaceField: ...
    def divergence(self, field: FaceField) -> FormChain[Literal[0]]: ...
    def first_frame_axes_numpy_copy(self) -> NDArray[np.float64]: ...
    def second_frame_axes_numpy_copy(self) -> NDArray[np.float64]: ...
    def face_unit_normals(self) -> FaceField: ...
    def uniform_vertex_normals(self) -> VertexField: ...
    def tip_angle_vertex_normals(self) -> VertexField: ...
    def sphere_inscribed_vertex_normals(self) -> VertexField: ...
    def surface_area_gradient(self) -> VertexField: ...
    def volume_gradient(self) -> VertexField: ...
    def gaussian_curvature_measure(self) -> FormElement[Any, Any]: ...
    def mean_curvature_vectors(self, metric: Metric[Any]) -> VertexField: ...
    def conformal_map(
        self,
        anchors: tuple[int, int],
        *,
        limit: GeometryLimit | None = None,
        policy: Policy | None = None,
        cancellation: CancellationToken | None = None,
    ) -> ConformalMap: ...
    def levi_civita(self) -> Connection: ...
    def connection(
        self, symmetry_order: int, deviations: NDArray[np.float64]
    ) -> Connection: ...
    def direction_field(
        self,
        symmetry_order: int,
        metric: Metric[Any],
        harmonic_basis: HarmonicBasis,
        dual_cycles: DualCycles,
        charges: Element[Space[int, Cochain, Literal[0]]],
        generator_turns: Sequence[int],
        anchor_angle: float,
        *,
        policy: Policy | None = None,
        cancellation: CancellationToken | None = None,
    ) -> Direction: ...
    def boundary_direction(
        self,
        symmetry_order: int,
        metric: Metric[Any],
        boundary_angle_offset: float,
        *,
        policy: Policy | None = None,
        cancellation: CancellationToken | None = None,
    ) -> Direction: ...

class VectorField[Degree: int]:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def geometry(self) -> Geometry[Any]: ...
    @property
    def entity_count(self) -> int: ...
    @property
    def fiber_dimension(self) -> int: ...
    @property
    def support_degree(self) -> Degree: ...
    def values_numpy_copy(self) -> NDArray[np.float64]: ...
    def normalized(self) -> VectorField[Degree]: ...

type VertexField = VectorField[Literal[0]]
type FaceField = VectorField[Literal[2]]

class Connection:
    @property
    def surface(self) -> TriangleSurface: ...
    @property
    def symmetry_order(self) -> int: ...
    def interior_edge_indices_numpy_copy(self) -> NDArray[np.int64]: ...
    def transports_numpy_copy(self) -> NDArray[np.float64]: ...
    def holonomy(self, cycles: DualCycles) -> Holonomy: ...
    def require_integrable(self) -> IntegrableConnection: ...

class DualCycles:
    @property
    def rank(self) -> int: ...
    def generator_edge_indices_numpy_copy(self) -> NDArray[np.int64]: ...
    def cocycle(self, index: int) -> Element[Space[int, Cochain, Literal[1]]]: ...

class Holonomy:
    @property
    def local_error(self) -> float: ...
    @property
    def generator_error(self) -> float: ...
    @property
    def limit(self) -> float: ...

class IntegrableConnection:
    @property
    def connection(self) -> Connection: ...
    @property
    def crossing_error(self) -> float: ...
    def direction(self, anchor_angle: float) -> Direction: ...

class Direction:
    @property
    def connection(self) -> IntegrableConnection: ...
    @property
    def symmetry_order(self) -> int: ...
    def power_directions_numpy_copy(self) -> NDArray[np.float64]: ...
    def ambient_branch_numpy_copy(self, branch: int) -> FaceField: ...
    def singularities(self) -> Singularities: ...

class Singularities:
    @property
    def symmetry_order(self) -> int: ...
    @property
    def charges(self) -> Element[Space[int, Cochain, Literal[0]]]: ...
    def boundary_turns_python_copy(self) -> tuple[int, ...]: ...
    @property
    def maximum_quantization_residual(self) -> float: ...
    @property
    def residual_limit(self) -> float: ...

class HalfedgeSurface:
    @staticmethod
    def from_complex(
        complex: Complex,
        *,
        limit: ChainLawLimit = ...,
    ) -> tuple[HalfedgeSurface, ChainIsomorphism[int]]: ...
    @staticmethod
    def from_permutations(
        next: object, twin: object, *, exterior_faces: object | None = None
    ) -> HalfedgeSurface: ...
    @property
    def halfedge_count(self) -> int: ...
    @property
    def vertex_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def face_orbit_count(self) -> int: ...
    @property
    def material_face_count(self) -> int: ...
    @property
    def exterior_face_count(self) -> int: ...
    @property
    def boundary_component_count(self) -> int: ...
    @property
    def connected_component_count(self) -> int: ...
    @property
    def euler_characteristic(self) -> int: ...
    @property
    def genus(self) -> int | None: ...
    def next_numpy_copy(self) -> NDArray[np.int64]: ...
    def twin_numpy_copy(self) -> NDArray[np.int64]: ...
    def vertex_of_numpy_copy(self) -> NDArray[np.int64]: ...
    def edge_of_numpy_copy(self) -> NDArray[np.int64]: ...
    def face_of_numpy_copy(self) -> NDArray[np.int64]: ...
    def boundary_cycles_numpy_copy(
        self,
    ) -> tuple[NDArray[np.int64], NDArray[np.int64], NDArray[np.int64]]: ...
    def boundary_scipy_copy(self, degree: int) -> Any: ...
    def to_complex(
        self, *, limit: ChainLawLimit = ...
    ) -> tuple[Complex, ChainIsomorphism[int]]: ...
    def chain_complex(self) -> ChainComplex[int]: ...

class Complex:
    @staticmethod
    def from_maximal_simplices(
        maximal_simplices: object, *, vertex_count: int | None = None
    ) -> Complex: ...
    @property
    def vertex_count(self) -> int: ...
    @property
    def dimension(self) -> int: ...
    def simplex_count(self, degree: int) -> int: ...
    def orientations_numpy_copy(self, degree: int) -> NDArray[np.int8]: ...
    def simplices_numpy_copy(self, degree: int) -> NDArray[np.int64]: ...
    def boundary_parts_numpy_copy(
        self, degree: int
    ) -> tuple[
        NDArray[np.int8],
        NDArray[np.int32] | NDArray[np.int64],
        NDArray[np.int32] | NDArray[np.int64],
        tuple[int, int],
    ]: ...
    def boundary_scipy_copy(self, degree: int) -> Any: ...
    def triangle_manifold(self) -> Self: ...
    def codimension_one_regular(self) -> Self: ...
    def oriented(self) -> Self: ...
    def connected(self) -> Self: ...
    def with_boundary(self) -> Self: ...
    def without_boundary(self) -> Self: ...
    def require_triangle(self) -> None: ...
    def require_regular(self) -> None: ...
    def require_oriented(self) -> None: ...
    def require_connected(self) -> None: ...
    def require_with_boundary(self) -> None: ...
    def require_without_boundary(self) -> None: ...
    def boundary_mask_numpy_copy(self, degree: int) -> NDArray[np.bool_]: ...
    def disk_boundary_vertices_numpy_copy(self) -> NDArray[np.int64]: ...
    def boundary_subset(self) -> Subset[Self]: ...
    def subset(self, masks: object) -> Subset[Self]: ...
    def selection(self, degree: int, indices: object) -> Selection: ...
    def shares_data_with(self, other: Complex) -> bool: ...
    def chain_complex(self) -> ChainComplex[int]: ...
    def binary64_chain_space[Degree: int](
        self, degree: Degree, *, indices: NDArray[np.integer] | None = None
    ) -> FormSpace[Literal["chain"], Degree]: ...
    def binary64_cochain_space[Degree: int](
        self, degree: Degree, *, indices: NDArray[np.integer] | None = None
    ) -> FormSpace[Literal["cochain"], Degree]: ...
    def dual_cycles(self) -> DualCycles: ...

class Subset[K: _GeometryDomain]:
    @property
    def topology(self) -> K: ...
    def mask_numpy_copy(self, degree: int) -> NDArray[np.bool_]: ...
    def owned_copy(self) -> Subset[K]: ...
    def closure(self) -> Subset[K]: ...
    def star(self) -> Subset[K]: ...
    def link(self) -> Subset[K]: ...
    def is_pure(self, degree: int) -> bool: ...
    def same_members(self, other: Subset[K]) -> bool: ...

class Selection:
    @property
    def topology(self) -> Complex: ...
    @property
    def degree(self) -> int: ...
    @property
    def size(self) -> int: ...
    def indices_numpy_copy(self) -> NDArray[np.int64]: ...
    def complement(self) -> Selection: ...
    def same_selection(self, other: Selection) -> bool: ...

def topological_boundary(complex: Complex) -> Subset[Complex]: ...

class _Topology:
    Complex: type[Complex]
    Subset: type[Subset[Any]]
    Selection: type[Selection]
    HalfedgeSurface: type[HalfedgeSurface]
    SimplicialError: type[SimplicialError]
    HalfedgeError: type[HalfedgeError]
    topological_boundary: Callable[[Complex], Subset[Complex]]

class _Chain:
    IntegerRing: type[IntegerRing]
    RationalField: type[RationalField]
    ZZ: IntegerRing
    QQ: RationalField
    Chain: type[Chain]
    Cochain: type[Cochain]
    BigIntEncoding: type[BigIntEncoding]
    ReducedFractionEncoding: type[ReducedFractionEncoding]
    Space: type[Space[Any, Any, int]]
    Element: type[Element[Any]]
    LinearMap: type[LinearMap[Any, Any]]
    ChainComplex: type[ChainComplex[Any]]
    CochainComplex: type[CochainComplex[Any]]
    ChainIsomorphism: type[ChainIsomorphism[Any]]
    ChainError: type[ChainError]
    ChainLawLimit: type[ChainLawLimit]
    DEFAULT_LAW_LIMIT: ChainLawLimit
    CsrEstimate: type[CsrEstimate]
    CsrBuildLimit: type[CsrBuildLimit]
    Csr: type[Csr[Any, Any, Any]]
    IntegerCsrParts: type[IntegerCsrParts]
    RationalCsrParts: type[RationalCsrParts]
    HomologyError: type[HomologyError]
    HomologyLimit: type[HomologyLimit]
    DEFAULT_HOMOLOGY_LIMIT: HomologyLimit
    HomologyGroup: type[HomologyGroup[int]]
    IntegralHomology: type[IntegralHomology]
    analyze_integral_homology: Callable[
        [ChainComplex[int], Iterable[int]], IntegralHomology
    ]

class _Form:
    Space: type[FormSpace[Any, int]]
    Element: type[FormElement[Any, int]]
    Operator: type[FormOperator[Any, int, Any, int]]
    ElementError: type[FormElementError]
    OperatorError: type[OperatorError]
    ChainSpace: type[FormSpace[Literal["chain"], int]]
    CochainSpace: type[FormSpace[Literal["cochain"], int]]
    Chain: type[FormElement[Literal["chain"], int]]
    Cochain: type[FormElement[Literal["cochain"], int]]

class _Geometry:
    Geometry: type[Geometry[Any]]
    Metric: type[Metric[Any]]
    Limit: type[GeometryLimit]
    DEFAULT_LIMIT: GeometryLimit
    GeometryError: type[GeometryError]
    SurfaceError: type[SurfaceError]
    TriangleSurface: type[TriangleSurface]
    VectorField: type[VectorField[int]]
    VertexField: type[VectorField[Literal[0]]]
    FaceField: type[VectorField[Literal[2]]]
    FlowStep: type[FlowStep]
    ConformalMap: type[ConformalMap]

class _Solve:
    StorageLimit: type[StorageLimit]
    WorkLimit: type[WorkLimit]
    Executor: type[Executor]
    Policy: type[Policy]
    CancellationToken: type[CancellationToken]
    Problem: type[Problem[Any]]
    Prepared: type[Prepared[Any]]
    Workspace: type[Workspace]
    ProblemError: type[ProblemError]
    SolveError: type[SolveError]
    PoissonResult: type[PoissonResult]
    DirichletResult: type[DirichletResult]
    HeatResult: type[HeatResult]

class _Field:
    DualCycles: type[DualCycles]
    HodgeDecomposition: type[HodgeDecomposition]
    HarmonicBasis: type[HarmonicBasis]
    Connection: type[Connection]
    Holonomy: type[Holonomy]
    IntegrableConnection: type[IntegrableConnection]
    Direction: type[Direction]
    Singularities: type[Singularities]

topology: _Topology
chain: _Chain
form: _Form
geometry: _Geometry
solve: _Solve
field: _Field
