"""Typing surface for the private mandatory native extension."""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray
from collections.abc import Iterable, Mapping
from fractions import Fraction
from typing import Any, Literal, Never, Protocol, Self, final, overload

from scipy.sparse import csr_array

type ExactScalar = int | Fraction
type Coordinates[Scalar: ExactScalar] = (
    Mapping[int, Scalar] | Iterable[tuple[int, Scalar]]
)

class ChainError(ValueError):
    @property
    def reason(self) -> str: ...
    @property
    def details(self) -> Mapping[str, object]: ...

class ChainLawLimit:
    def __init__(
        self,
        *,
        retained_logical_bytes: int = ...,
        peak_live_logical_bytes: int = ...,
        terms: int = ...,
    ) -> None: ...
    @property
    def retained_logical_bytes(self) -> int: ...
    @property
    def peak_live_logical_bytes(self) -> int: ...
    @property
    def terms(self) -> int: ...

class IntegerRing: ...
class RationalField: ...

ZZ: IntegerRing
QQ: RationalField

class Chain:
    variance: Literal["chain"]

class Cochain:
    variance: Literal["cochain"]

class BigIntEncoding:
    _kind: Literal["bigint"]

class ReducedFractionEncoding:
    _kind: Literal["fraction"]

class Space[Scalar: ExactScalar, Variance, Degree: int]:
    _variance_proof: Variance
    @property
    def degree(self) -> int: ...
    @property
    def dimension(self) -> int: ...
    def element(self, coordinates: Coordinates[Scalar]) -> Element[Self]: ...

class Element[SpaceType: Space[Any, Any, int]]:
    _proof: SpaceType
    @property
    def degree(self) -> int: ...
    @property
    def dimension(self) -> int: ...
    def to_python_copy(self) -> tuple[tuple[int, ...], tuple[ExactScalar, ...]]: ...
    def evaluate[Scalar: ExactScalar, Degree: int](
        self: Element[Space[Scalar, Cochain, Degree]],
        chain: Element[Space[Scalar, Chain, Degree]],
    ) -> Scalar: ...
    def cup[Scalar: ExactScalar](
        self: Element[Space[Scalar, Cochain, int]],
        other: Element[Space[Scalar, Cochain, int]],
    ) -> Element[Space[Scalar, Cochain, int]]: ...
    def wedge(
        self: Element[Space[Fraction, Cochain, int]],
        other: Element[Space[Fraction, Cochain, int]],
    ) -> Element[Space[Fraction, Cochain, int]]: ...

class LinearMap[SourceSpace: Space[Any, Any, int], TargetSpace: Space[Any, Any, int]]:
    @property
    def source(self) -> SourceSpace: ...
    @property
    def target(self) -> TargetSpace: ...
    def apply(self, value: Element[SourceSpace]) -> Element[TargetSpace]: ...
    @overload
    def dual[Scalar: ExactScalar, SourceDegree: int, TargetDegree: int](
        self: LinearMap[
            Space[Scalar, Chain, SourceDegree],
            Space[Scalar, Chain, TargetDegree],
        ],
    ) -> LinearMap[
        Space[Scalar, Cochain, TargetDegree],
        Space[Scalar, Cochain, SourceDegree],
    ]: ...
    @overload
    def dual[Scalar: ExactScalar, SourceDegree: int, TargetDegree: int](
        self: LinearMap[
            Space[Scalar, Cochain, SourceDegree],
            Space[Scalar, Cochain, TargetDegree],
        ],
    ) -> LinearMap[
        Space[Scalar, Chain, TargetDegree],
        Space[Scalar, Chain, SourceDegree],
    ]: ...
    def compose[
        Initial: Space[Any, Any, int],
        Middle: Space[Any, Any, int],
        Final: Space[Any, Any, int],
    ](
        self: LinearMap[Middle, Final], before: LinearMap[Initial, Middle]
    ) -> LinearMap[Initial, Final]: ...
    def over[SourceVariance, TargetVariance, SourceDegree: int, TargetDegree: int](
        self: LinearMap[
            Space[int, SourceVariance, SourceDegree],
            Space[int, TargetVariance, TargetDegree],
        ],
        coefficients: RationalField,
    ) -> LinearMap[
        Space[Fraction, SourceVariance, SourceDegree],
        Space[Fraction, TargetVariance, TargetDegree],
    ]: ...

class ChainComplex[Scalar: ExactScalar]:
    _coefficient_proof: Scalar
    @property
    def coefficient_system(self) -> str: ...
    @property
    def dimension(self) -> int: ...
    def same_owner(self, other: ChainComplex[Any]) -> bool: ...
    def __getitem__[Degree: int](
        self, degree: Degree
    ) -> Space[Scalar, Chain, Degree]: ...
    def dual(self) -> CochainComplex[Scalar]: ...
    def boundary(
        self, degree: int
    ) -> LinearMap[Space[Scalar, Chain, int], Space[Scalar, Chain, int]]: ...
    def over(
        self: ChainComplex[int], coefficients: RationalField
    ) -> ChainComplex[Fraction]: ...

class CochainComplex[Scalar: ExactScalar]:
    _coefficient_proof: Scalar
    def __getitem__[Degree: int](
        self, degree: Degree
    ) -> Space[Scalar, Cochain, Degree]: ...
    def coboundary(
        self, degree: int
    ) -> LinearMap[Space[Scalar, Cochain, int], Space[Scalar, Cochain, int]]: ...

class ChainIsomorphism[Scalar: ExactScalar]:
    @property
    def source(self) -> ChainComplex[Scalar]: ...
    @property
    def target(self) -> ChainComplex[Scalar]: ...
    def forward[Degree: int](
        self, degree: Degree
    ) -> LinearMap[Space[Scalar, Chain, Degree], Space[Scalar, Chain, Degree]]: ...
    def inverse[Degree: int](
        self, degree: Degree
    ) -> LinearMap[Space[Scalar, Chain, Degree], Space[Scalar, Chain, Degree]]: ...

class CsrEstimate:
    shape: tuple[int, int]
    nnz_bound: int
    coefficient_bits_bound: int
    retained_logical_bytes_bound: int
    peak_live_logical_bytes_bound: int
    scratch_entries_bound: int
    scalar_steps_bound: int
    canonicalization_required: bool
    def as_limit(self) -> CsrBuildLimit: ...

class CsrBuildLimit:
    retained_logical_bytes: int
    peak_live_logical_bytes: int
    coefficient_bits: int
    scalar_steps: int
    def replace(
        self,
        *,
        retained_logical_bytes: int | None = None,
        peak_live_logical_bytes: int | None = None,
        coefficient_bits: int | None = None,
        scalar_steps: int | None = None,
    ) -> CsrBuildLimit: ...

class IntegerCsrParts:
    row_offsets: NDArray[Any]
    column_indices: NDArray[Any]
    coefficients: tuple[int, ...]
    shape: tuple[int, int]

class RationalCsrParts:
    row_offsets: NDArray[Any]
    column_indices: NDArray[Any]
    numerators: tuple[int, ...]
    denominators: tuple[int, ...]
    shape: tuple[int, int]

class CsrRepresentation[
    SourceSpace: Space[Any, Any, int],
    TargetSpace: Space[Any, Any, int],
    Encoding,
]:
    represented_map: LinearMap[SourceSpace, TargetSpace]
    encoding: type[Encoding]
    @staticmethod
    def estimate[
        Source: Space[Any, Any, int],
        Target: Space[Any, Any, int],
        EncodingType,
    ](map_: LinearMap[Source, Target], encoding: type[EncodingType]) -> CsrEstimate: ...
    @classmethod
    @overload
    def build[Source: Space[Any, Any, int], Target: Space[Any, Any, int]](
        cls,
        map_: LinearMap[Source, Target],
        encoding: type[BigIntEncoding],
        limit: CsrBuildLimit,
    ) -> CsrRepresentation[Source, Target, BigIntEncoding]: ...
    @classmethod
    @overload
    def build[Source: Space[Any, Any, int], Target: Space[Any, Any, int]](
        cls,
        map_: LinearMap[Source, Target],
        encoding: type[ReducedFractionEncoding],
        limit: CsrBuildLimit,
    ) -> CsrRepresentation[Source, Target, ReducedFractionEncoding]: ...
    def apply(self, value: Element[SourceSpace]) -> Element[TargetSpace]: ...
    @overload
    def to_python_copy(
        self: CsrRepresentation[SourceSpace, TargetSpace, BigIntEncoding],
    ) -> IntegerCsrParts: ...
    @overload
    def to_python_copy(
        self: CsrRepresentation[SourceSpace, TargetSpace, ReducedFractionEncoding],
    ) -> RationalCsrParts: ...
    def to_scipy_int64_copy(
        self: CsrRepresentation[SourceSpace, TargetSpace, BigIntEncoding],
    ) -> csr_array: ...

class HomologyError(ChainError):
    @property
    def reason(self) -> str: ...
    @property
    def details(self) -> Mapping[str, object]: ...

@final
class HomologyLimit:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def retained_logical_bytes(self) -> int: ...
    @property
    def peak_live_logical_bytes(self) -> int: ...
    @property
    def coefficient_bits(self) -> int: ...
    @property
    def smith_steps(self) -> int: ...
    def replace(
        self,
        *,
        retained_logical_bytes: int | None = None,
        peak_live_logical_bytes: int | None = None,
        coefficient_bits: int | None = None,
        smith_steps: int | None = None,
    ) -> HomologyLimit: ...

DEFAULT_HOMOLOGY_LIMIT: HomologyLimit

@final
class HomologyGroup[Degree: int]:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def degree(self) -> Degree: ...
    @property
    def free_rank(self) -> int: ...
    @property
    def torsion_orders(self) -> tuple[int, ...]: ...
    def free_cycle(self, index: int) -> Element[Space[int, Chain, Degree]]: ...
    def torsion_cycle(self, index: int) -> Element[Space[int, Chain, Degree]]: ...
    def torsion_bound(self, index: int) -> Element[Space[int, Chain, Degree]]: ...

@final
class IntegralHomology:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def degrees(self) -> tuple[int, ...]: ...
    def __getitem__[Degree: int](self, degree: Degree) -> HomologyGroup[Degree]: ...

def analyze_integral_homology(
    chain_complex: ChainComplex[int],
    degrees: Iterable[int],
    *,
    limit: HomologyLimit = DEFAULT_HOMOLOGY_LIMIT,
) -> IntegralHomology: ...

DEFAULT_CHAIN_LAW_LIMIT: ChainLawLimit

class SimplicialError(ValueError):
    @property
    def reason(self) -> str: ...
    @property
    def details(self) -> Mapping[str, int | str]: ...

class HalfedgeError(SimplicialError): ...

class _GeometryDomain(Protocol):
    @property
    def vertex_count(self) -> int: ...
    @property
    def dimension(self) -> int: ...
    def simplex_count(self, degree: int) -> int: ...
    def simplices(self, degree: int) -> NDArray[np.int64]: ...
    def shares_data_with(self, other: Complex) -> bool: ...

class GeometryError(ValueError):
    reason: str
    details: Mapping[str, int | str]

class Binary64ElementError(ValueError):
    reason: str

class OperatorError(ValueError):
    reason: str

class ProblemError(ValueError):
    reason: str
    details: Mapping[str, int | str]

class SolveError(ValueError):
    reason: str
    details: Mapping[str, int | str]

class SurfaceError(ValueError):
    reason: str
    details: Mapping[str, int | str]

class RealizationLimit:
    def __init__(
        self,
        *,
        retained_logical_bytes: int = ...,
        peak_live_logical_bytes: int = ...,
        coefficient_bits: int = ...,
        exact_steps: int = ...,
    ) -> None: ...
    @property
    def retained_logical_bytes(self) -> int: ...
    @property
    def peak_live_logical_bytes(self) -> int: ...
    @property
    def coefficient_bits(self) -> int: ...
    @property
    def exact_steps(self) -> int: ...

DEFAULT_REALIZATION_LIMIT: RealizationLimit

class Binary64Space[Variance: str, Degree: int]:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def degree(self) -> Degree: ...
    @property
    def size(self) -> int: ...
    @property
    def variance(self) -> Variance: ...
    @property
    def is_full(self) -> bool: ...
    def same_space(self, other: Binary64Space[Any, Any]) -> bool: ...
    def admit_numpy(
        self, coefficients: NDArray[np.float64]
    ) -> Binary64Element[Variance, Degree]: ...
    def realize_integral(self, exact: object) -> Binary64Element[Variance, Degree]: ...
    def identity(self) -> LinearOperator[Variance, Degree, Variance, Degree]: ...
    def zero_to[TargetVariance: str, TargetDegree: int](
        self, target: Binary64Space[TargetVariance, TargetDegree]
    ) -> LinearOperator[Variance, Degree, TargetVariance, TargetDegree]: ...
    def restriction(self) -> LinearOperator[Variance, Degree, Variance, Degree]: ...
    def extension_by_zero(
        self,
    ) -> LinearOperator[Variance, Degree, Variance, Degree]: ...
    def exterior_derivative(
        self,
    ) -> LinearOperator[Variance, Degree, Variance, int]: ...

class Binary64Element[Variance: str, Degree: int]:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def space(self) -> Binary64Space[Variance, Degree]: ...
    def coefficients_numpy_copy(self) -> NDArray[np.float64]: ...
    def __neg__(self) -> Binary64Element[Variance, Degree]: ...
    def apply[TargetVariance: str, TargetDegree: int](
        self,
        operator: LinearOperator[Variance, Degree, TargetVariance, TargetDegree],
    ) -> Binary64Element[TargetVariance, TargetDegree]: ...
    def wedge(
        self: Binary64Element[Literal["cochain"], int],
        other: Binary64Element[Literal["cochain"], int],
    ) -> Binary64Element[Literal["cochain"], int]: ...

class LinearOperator[
    SourceVariance: str,
    SourceDegree: int,
    TargetVariance: str,
    TargetDegree: int,
]:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def source(self) -> Binary64Space[SourceVariance, SourceDegree]: ...
    @property
    def target(self) -> Binary64Space[TargetVariance, TargetDegree]: ...
    @property
    def execution_steps(self) -> int: ...
    def same_identity(self, other: LinearOperator[Any, Any, Any, Any]) -> bool: ...
    def apply(
        self, value: Binary64Element[SourceVariance, SourceDegree]
    ) -> Binary64Element[TargetVariance, TargetDegree]: ...
    def compose[BeforeVariance: str, BeforeDegree: int](
        self,
        before: LinearOperator[
            BeforeVariance, BeforeDegree, SourceVariance, SourceDegree
        ],
    ) -> LinearOperator[BeforeVariance, BeforeDegree, TargetVariance, TargetDegree]: ...
    def to_scipy_copy(self) -> Any: ...
    def dirichlet(
        self,
        rhs: Binary64Element[TargetVariance, TargetDegree],
        prescribed: Binary64Element[TargetVariance, TargetDegree],
    ) -> Problem[DirichletSolution]: ...

type Binary64ChainSpace[Degree: int] = Binary64Space[Literal["chain"], Degree]
type Binary64CochainSpace[Degree: int] = Binary64Space[Literal["cochain"], Degree]
type Binary64Chain[Degree: int] = Binary64Element[Literal["chain"], Degree]
type Binary64Cochain[Degree: int] = Binary64Element[Literal["cochain"], Degree]

class EuclideanRealization[K: _GeometryDomain]:
    def __init__(
        self,
        complex: K,
        positions: NDArray[np.float64],
        *,
        limit: RealizationLimit = DEFAULT_REALIZATION_LIMIT,
    ) -> None: ...
    @staticmethod
    def from_positions[Domain: _GeometryDomain](
        complex: Domain,
        positions: NDArray[np.float64],
        *,
        limit: RealizationLimit = DEFAULT_REALIZATION_LIMIT,
    ) -> EuclideanRealization[Domain]: ...
    @property
    def complex(self) -> K: ...
    @property
    def ambient_dimension(self) -> int: ...
    def positions_numpy_copy(self) -> NDArray[np.float64]: ...
    def primal_measures_numpy_copy(self, degree: int) -> NDArray[np.float64]: ...
    def dual_measures_numpy_copy(self, degree: int) -> NDArray[np.float64]: ...
    def _dual_signs(self, degree: int) -> NDArray[np.int8]: ...
    def positive_metric(self) -> PositiveMetric[K]: ...

class PositiveMetric[K: _GeometryDomain]:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def realization(self) -> EuclideanRealization[K]: ...
    def hodge_coefficients_numpy_copy(self, degree: int) -> NDArray[np.float64]: ...
    def riesz(self, degree: int) -> LinearOperator[Any, Any, Any, Any]: ...
    def inverse_riesz(self, degree: int) -> LinearOperator[Any, Any, Any, Any]: ...
    def codifferential(self, degree: int) -> LinearOperator[Any, Any, Any, Any]: ...
    def laplacian(self, degree: int) -> LinearOperator[Any, Any, Any, Any]: ...
    def harmonic_one_form_basis(
        self,
        group: HomologyGroup[Literal[1]],
        *,
        executor: NativeExecutor | None = None,
        storage: StorageLimit | None = None,
        work: WorkLimit | None = None,
        cancellation: CancellationToken | None = None,
    ) -> HarmonicOneFormBasis: ...
    def mean_zero_poisson_density[Degree: int](
        self, density: Binary64Cochain[Degree]
    ) -> Problem[PoissonSolution]: ...
    def mean_zero_poisson_load[Degree: int](
        self, load: Binary64Chain[Degree]
    ) -> Problem[PoissonSolution]: ...
    def harmonic_extension(
        self, values: Binary64Element[Any, Any]
    ) -> Problem[DirichletSolution]: ...
    def hodge_decomposition(
        self, source: Binary64Element[Any, Any]
    ) -> Problem[HodgeDecomposition]: ...
    def heat_evolution(
        self, source: Binary64Element[Any, Any], time_step: float
    ) -> Problem[HeatSolution]: ...
    def frozen_mean_curvature_flow(
        self,
        time_step: float,
        *,
        realization_limit: RealizationLimit | None = None,
        executor: NativeExecutor | None = None,
        storage: StorageLimit | None = None,
        work: WorkLimit | None = None,
        cancellation: CancellationToken | None = None,
    ) -> FlowStep: ...

class StorageLimit:
    def __init__(
        self, retained_logical_bytes: int, peak_live_logical_bytes: int
    ) -> None: ...
    @property
    def retained_logical_bytes(self) -> int: ...
    @property
    def peak_live_logical_bytes(self) -> int: ...

class WorkLimit:
    def __init__(self, steps: int) -> None: ...
    @property
    def steps(self) -> int: ...

class NativeExecutor:
    @staticmethod
    def sequential() -> NativeExecutor: ...

class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def is_cancelled(self) -> bool: ...

class Problem[SolutionT]:
    def __new__(cls, _token: Never, /) -> Self: ...
    def prepare(
        self,
        *,
        executor: NativeExecutor | None = None,
        storage: StorageLimit | None = None,
        work: WorkLimit | None = None,
        cancellation: CancellationToken | None = None,
    ) -> PreparedProblem[SolutionT]: ...

class PreparedProblem[SolutionT]:
    def __new__(cls, _token: Never, /) -> Self: ...
    def workspace_for(
        self, problem: Problem[SolutionT], *, storage: StorageLimit | None = None
    ) -> SolveWorkspace: ...
    def solve(
        self,
        problem: Problem[SolutionT],
        workspace: SolveWorkspace,
        *,
        work: WorkLimit | None = None,
        cancellation: CancellationToken | None = None,
    ) -> SolutionT: ...

class SolveWorkspace:
    def __new__(cls, _token: Never, /) -> Self: ...

class PoissonSolution:
    @property
    def potential(self) -> Binary64Element[Any, Any]: ...
    @property
    def residual_bound(self) -> float: ...
    @property
    def gauge_bound(self) -> float: ...
    @property
    def exact_fallback_rows(self) -> int: ...

class DirichletSolution:
    @property
    def value(self) -> Binary64Element[Any, Any]: ...
    @property
    def residual_bound(self) -> float: ...
    @property
    def exact_fallback_rows(self) -> int: ...

class HodgeDecomposition:
    @property
    def exact(self) -> Binary64Element[Any, Any]: ...
    @property
    def coexact(self) -> Binary64Element[Any, Any]: ...
    @property
    def harmonic(self) -> Binary64Element[Any, Any]: ...
    @property
    def reconstruction_bound(self) -> float: ...
    @property
    def orthogonality_bound(self) -> float: ...

@final
class HarmonicOneFormBasis:
    @property
    def rank(self) -> int: ...
    @property
    def forms(self) -> tuple[Binary64Cochain[Literal[1]], ...]: ...
    @property
    def maximum_closedness_residual(self) -> float: ...
    @property
    def maximum_coclosedness_residual(self) -> float: ...
    @property
    def maximum_identity_period_residual(self) -> float: ...
    @property
    def residual_limit(self) -> float: ...

class HeatSolution:
    @property
    def value(self) -> Binary64Element[Any, Any]: ...
    @property
    def residual_bound(self) -> float: ...
    @property
    def mass_residual_bound(self) -> float: ...
    @property
    def energy_before(self) -> float: ...
    @property
    def energy_after(self) -> float: ...
    @property
    def exact_fallback_rows(self) -> int: ...

class FlowStep:
    @property
    def target(self) -> EuclideanRealization[Any]: ...
    @property
    def energy_before(self) -> float: ...
    @property
    def energy_after(self) -> float: ...
    @property
    def residual_bound(self) -> float: ...
    @property
    def centroid_residual_bound(self) -> float: ...

class LeastSquaresConformalMapSolution:
    @property
    def realization(self) -> EuclideanRealization[Any]: ...
    @property
    def required_rank(self) -> int: ...
    @property
    def observed_rank(self) -> int: ...
    @property
    def condition_indicator(self) -> float: ...
    @property
    def residual_bound(self) -> float: ...
    @property
    def minimum_normalized_signed_twice_area(self) -> float: ...
    @property
    def exact_fallback_faces(self) -> int: ...

class TriangleSurface:
    @staticmethod
    def admit(realization: EuclideanRealization[Any]) -> TriangleSurface: ...
    @property
    def realization(self) -> EuclideanRealization[Any]: ...
    @property
    def face_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    def vertex_vectors(self, values: NDArray[np.float64]) -> EntityVectors: ...
    def face_vectors(self, values: NDArray[np.float64]) -> EntityVectors: ...
    def gradient(self, source: Binary64Cochain[int]) -> FaceVectors: ...
    def divergence(self, field: FaceVectors) -> Binary64Chain[Literal[0]]: ...
    def first_frame_axes_numpy_copy(self) -> NDArray[np.float64]: ...
    def second_frame_axes_numpy_copy(self) -> NDArray[np.float64]: ...
    def face_unit_normals(self) -> EntityVectors: ...
    def uniform_vertex_normals(self) -> EntityVectors: ...
    def tip_angle_vertex_normals(self) -> EntityVectors: ...
    def sphere_inscribed_vertex_normals(self) -> EntityVectors: ...
    def surface_area_gradient(self) -> EntityVectors: ...
    def volume_gradient(self) -> EntityVectors: ...
    def gaussian_curvature_measure(self) -> Binary64Element[Any, Any]: ...
    def mean_curvature_vectors(self, metric: PositiveMetric[Any]) -> EntityVectors: ...
    def least_squares_conformal_map(
        self,
        anchors: tuple[int, int],
        *,
        realization_limit: RealizationLimit | None = None,
        executor: NativeExecutor | None = None,
        storage: StorageLimit | None = None,
        work: WorkLimit | None = None,
        cancellation: CancellationToken | None = None,
    ) -> LeastSquaresConformalMapSolution: ...
    def levi_civita_connection(self) -> SurfaceConnection: ...
    def connection(self, deviations: NDArray[np.float64]) -> SurfaceConnection: ...

class EntityVectors:
    def __new__(cls, _token: Never, /) -> Self: ...
    @property
    def realization(self) -> EuclideanRealization[Any]: ...
    @property
    def entity_count(self) -> int: ...
    @property
    def fiber_dimension(self) -> int: ...
    @property
    def is_vertex_supported(self) -> bool: ...
    @property
    def is_face_supported(self) -> bool: ...
    def vectors_numpy_copy(self) -> NDArray[np.float64]: ...
    def normalized(self) -> EntityVectors: ...

type VertexVectors = EntityVectors
type FaceVectors = EntityVectors

class SurfaceConnection:
    @property
    def surface(self) -> TriangleSurface: ...
    def transports_numpy_copy(self) -> NDArray[np.float64]: ...
    def compose(self, after: SurfaceConnection) -> SurfaceConnection: ...
    def holonomy(self, cycles: IntegralDualCycleBasis) -> HolonomyEvidence: ...
    def require_integrable(
        self, cycles: IntegralDualCycleBasis
    ) -> IntegrableConnection: ...

class IntegralDualCycleBasis:
    @property
    def rank(self) -> int: ...
    def generator_edge_indices_numpy_copy(self) -> NDArray[np.int64]: ...
    def cocycle(self, index: int) -> Element[Space[int, Cochain, Literal[1]]]: ...

class HolonomyEvidence:
    @property
    def local_error(self) -> float: ...
    @property
    def generator_error(self) -> float: ...
    @property
    def limit(self) -> float: ...

class IntegrableConnection:
    @property
    def connection(self) -> SurfaceConnection: ...
    @property
    def crossing_error(self) -> float: ...
    def direction_field(self, anchor_phase: float) -> FaceDirectionField: ...

class FaceDirectionField:
    @property
    def connection(self) -> SurfaceConnection: ...
    @property
    def crossing_error(self) -> float: ...
    def directions_numpy_copy(self) -> NDArray[np.float64]: ...
    def ambient_vectors_numpy_copy(self) -> EntityVectors: ...

class HalfedgeSurface:
    @staticmethod
    def from_complex(
        complex: Complex,
        *,
        limit: ChainLawLimit = ...,
    ) -> tuple[HalfedgeSurface, SurfaceCorrespondence]: ...
    @staticmethod
    def from_permutations(
        next: object, twin: object, *, exterior_faces: object | None = None
    ) -> HalfedgeSurface: ...
    @property
    def halfedge_count(self) -> int: ...
    @property
    def vertex_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def face_orbit_count(self) -> int: ...
    @property
    def material_face_count(self) -> int: ...
    @property
    def exterior_face_count(self) -> int: ...
    @property
    def boundary_component_count(self) -> int: ...
    @property
    def connected_component_count(self) -> int: ...
    @property
    def euler_characteristic(self) -> int: ...
    @property
    def genus(self) -> int | None: ...
    def next(self) -> NDArray[np.int64]: ...
    def twin(self) -> NDArray[np.int64]: ...
    def vertex_of(self) -> NDArray[np.int64]: ...
    def edge_of(self) -> NDArray[np.int64]: ...
    def face_of(self) -> NDArray[np.int64]: ...
    def boundary_cycles(
        self,
    ) -> tuple[NDArray[np.int64], NDArray[np.int64], NDArray[np.int64]]: ...
    def boundary_matrix(self, degree: int) -> Any: ...
    def to_complex(
        self, *, limit: ChainLawLimit = ...
    ) -> tuple[Complex, SurfaceCorrespondence]: ...
    def chain_complex(self) -> ChainComplex[int]: ...

class SurfaceCorrespondence:
    @property
    def source(self) -> Complex | HalfedgeSurface: ...
    @property
    def target(self) -> Complex | HalfedgeSurface: ...
    @property
    def direction(self) -> str: ...
    def signed_permutation(
        self, degree: int
    ) -> tuple[NDArray[np.int64], NDArray[np.int8]]: ...
    def chain_isomorphism(self) -> ChainIsomorphism[int]: ...

class Complex:
    @staticmethod
    def from_maximal_simplices(
        maximal_simplices: object, *, vertex_count: int | None = None
    ) -> Complex: ...
    @property
    def vertex_count(self) -> int: ...
    @property
    def dimension(self) -> int: ...
    def simplex_count(self, degree: int) -> int: ...
    def orientations(self, degree: int) -> NDArray[np.int8]: ...
    def simplices(self, degree: int) -> NDArray[np.int64]: ...
    def boundary_parts(
        self, degree: int
    ) -> tuple[
        NDArray[np.int8],
        NDArray[np.int32] | NDArray[np.int64],
        NDArray[np.int32] | NDArray[np.int64],
        tuple[int, int],
    ]: ...
    def boundary_matrix(self, degree: int) -> Any: ...
    def triangle_manifold(self) -> Self: ...
    def codimension_one_regular(self) -> Self: ...
    def oriented(self) -> Self: ...
    def connected(self) -> Self: ...
    def with_boundary(self) -> Self: ...
    def without_boundary(self) -> Self: ...
    def require_triangle(self) -> None: ...
    def require_regular(self) -> None: ...
    def require_oriented(self) -> None: ...
    def require_connected(self) -> None: ...
    def require_with_boundary(self) -> None: ...
    def require_without_boundary(self) -> None: ...
    def boundary_mask(self, degree: int) -> NDArray[np.bool_]: ...
    def disk_boundary_vertices_numpy_copy(self) -> NDArray[np.int64]: ...
    def boundary_subset(self) -> SimplexSubset[Self]: ...
    def subset(self, masks: object) -> SimplexSubset[Self]: ...
    def selection(self, degree: int, indices: object) -> SimplexSelection: ...
    def shares_data_with(self, other: Complex) -> bool: ...
    def chain_complex(self) -> ChainComplex[int]: ...
    def binary64_chain_space[Degree: int](
        self, degree: Degree, *, indices: NDArray[np.integer] | None = None
    ) -> Binary64Space[Literal["chain"], Degree]: ...
    def binary64_cochain_space[Degree: int](
        self, degree: Degree, *, indices: NDArray[np.integer] | None = None
    ) -> Binary64Space[Literal["cochain"], Degree]: ...
    def integral_dual_cycle_basis(self) -> IntegralDualCycleBasis: ...

class SimplexSubset[K: _GeometryDomain]:
    @property
    def complex(self) -> K: ...
    def mask(self, degree: int) -> NDArray[np.bool_]: ...
    def owned_copy(self) -> SimplexSubset[K]: ...
    def closure(self) -> SimplexSubset[K]: ...
    def star(self) -> SimplexSubset[K]: ...
    def link(self) -> SimplexSubset[K]: ...
    def is_pure(self, degree: int) -> bool: ...
    def same_members(self, other: SimplexSubset[K]) -> bool: ...

class SimplexSelection:
    @property
    def complex(self) -> Complex: ...
    @property
    def degree(self) -> int: ...
    @property
    def size(self) -> int: ...
    def indices(self) -> NDArray[np.int64]: ...
    def complement(self) -> SimplexSelection: ...
    def same_selection(self, other: SimplexSelection) -> bool: ...

def topological_boundary(complex: Complex) -> SimplexSubset[Complex]: ...

ZZ: IntegerRing
QQ: RationalField
